package com.example.util

import android.content.Context
import android.content.Intent
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.RectF
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import android.net.Uri
import android.text.Layout
import android.text.StaticLayout
import android.text.TextPaint
import androidx.core.content.FileProvider
import com.example.data.local.AudioNote
import com.example.data.local.ChecklistItem
import com.example.ui.viewmodel.ActiveNoteState
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

object ExportManager {

    /**
     * Build formatted plain text representation
     */
    fun buildPlainText(
        title: String,
        polishedText: String,
        rawTranscript: String = "",
        summary: String = "",
        keyTakeaways: List<String> = emptyList(),
        checklist: List<ChecklistItem> = emptyList(),
        category: String = "General",
        createdAt: Long = System.currentTimeMillis()
    ): String {
        val dateStr = SimpleDateFormat("MMMM d, yyyy · h:mm a", Locale.getDefault()).format(Date(createdAt))
        return buildString {
            appendLine(title.uppercase(Locale.getDefault()))
            appendLine("Date: $dateStr | Category: $category")
            appendLine("=".repeat(50))
            appendLine()

            if (summary.isNotBlank()) {
                appendLine("EXECUTIVE SUMMARY:")
                appendLine(summary)
                appendLine()
                appendLine("-".repeat(50))
                appendLine()
            }

            appendLine("STRUCTURED CONTENT:")
            appendLine(polishedText)
            appendLine()

            if (keyTakeaways.isNotEmpty()) {
                appendLine("-".repeat(50))
                appendLine("KEY TAKEAWAYS:")
                keyTakeaways.forEach { takeaway ->
                    appendLine("• $takeaway")
                }
                appendLine()
            }

            if (checklist.isNotEmpty()) {
                appendLine("-".repeat(50))
                appendLine("ACTION CHECKLIST:")
                checklist.forEach { item ->
                    val status = if (item.isCompleted) "[X]" else "[ ]"
                    appendLine("$status ${item.text}")
                }
                appendLine()
            }

            if (rawTranscript.isNotBlank()) {
                appendLine("-".repeat(50))
                appendLine("ORIGINAL VOICE TRANSCRIPT:")
                appendLine(rawTranscript)
                appendLine()
            }

            appendLine("=".repeat(50))
            appendLine("Transcribed & structured with AudioPen AI")
        }
    }

    /**
     * Build structured Markdown document
     */
    fun buildMarkdown(
        title: String,
        polishedText: String,
        rawTranscript: String = "",
        summary: String = "",
        keyTakeaways: List<String> = emptyList(),
        checklist: List<ChecklistItem> = emptyList(),
        category: String = "General",
        formatStyle: String = "Classic",
        createdAt: Long = System.currentTimeMillis()
    ): String {
        val dateStr = SimpleDateFormat("yyyy-MM-dd HH:mm", Locale.getDefault()).format(Date(createdAt))
        return buildString {
            appendLine("# $title")
            appendLine()
            appendLine("> **Date:** $dateStr | **Category:** $category | **Format:** $formatStyle")
            appendLine()

            if (summary.isNotBlank()) {
                appendLine("## 💡 Executive Summary")
                appendLine(summary)
                appendLine()
            }

            appendLine("## 📝 Note Content")
            appendLine(polishedText)
            appendLine()

            if (keyTakeaways.isNotEmpty()) {
                appendLine("## 🎯 Key Takeaways")
                keyTakeaways.forEach { takeaway ->
                    appendLine("- $takeaway")
                }
                appendLine()
            }

            if (checklist.isNotEmpty()) {
                appendLine("## ✅ Action Checklist")
                checklist.forEach { item ->
                    val mark = if (item.isCompleted) "x" else " "
                    appendLine("- [$mark] ${item.text}")
                }
                appendLine()
            }

            if (rawTranscript.isNotBlank()) {
                appendLine("---")
                appendLine("### 🎙️ Original Spoken Transcript")
                appendLine("```")
                appendLine(rawTranscript)
                appendLine("```")
                appendLine()
            }

            appendLine("---")
            appendLine("*Generated by AudioPen AI Voice Memo App*")
        }
    }

    /**
     * Create a plain text (.txt) file in cache
     */
    fun createPlainTextFile(
        context: Context,
        title: String,
        content: String
    ): File {
        val safeTitle = title.replace("[^a-zA-Z0-9.-]".toRegex(), "_").take(30)
        val file = File(context.cacheDir, "${safeTitle}_export.txt")
        file.writeText(content)
        return file
    }

    /**
     * Create a markdown (.md) file in cache
     */
    fun createMarkdownFile(
        context: Context,
        title: String,
        markdownContent: String
    ): File {
        val safeTitle = title.replace("[^a-zA-Z0-9.-]".toRegex(), "_").take(30)
        val file = File(context.cacheDir, "${safeTitle}_export.md")
        file.writeText(markdownContent)
        return file
    }

    /**
     * Create a visually formatted PDF (.pdf) file in cache
     */
    fun createPdfFile(
        context: Context,
        title: String,
        polishedText: String,
        summary: String = "",
        keyTakeaways: List<String> = emptyList(),
        checklist: List<ChecklistItem> = emptyList(),
        category: String = "General",
        createdAt: Long = System.currentTimeMillis()
    ): File {
        val pdfDoc = PdfDocument()
        val pageWidth = 595 // Standard A4 width in points (72 dpi)
        val pageHeight = 842 // Standard A4 height in points (72 dpi)
        val margin = 40f
        val contentWidth = (pageWidth - (margin * 2)).toInt()

        var pageNumber = 1
        var pageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, pageNumber).create()
        var page = pdfDoc.startPage(pageInfo)
        var canvas = page.canvas

        var yOffset = margin

        fun newPageIfNeeded(requiredHeight: Float) {
            if (yOffset + requiredHeight > pageHeight - margin) {
                pdfDoc.finishPage(page)
                pageNumber++
                pageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, pageNumber).create()
                page = pdfDoc.startPage(pageInfo)
                canvas = page.canvas
                yOffset = margin

                // Draw header on subsequent pages
                val headerPaint = TextPaint().apply {
                    color = Color.DKGRAY
                    textSize = 9f
                    isAntiAlias = true
                }
                canvas.drawText("AudioPen Note: $title", margin, yOffset + 10f, headerPaint)
                val linePaint = Paint().apply {
                    color = Color.LTGRAY
                    strokeWidth = 1f
                }
                canvas.drawLine(margin, yOffset + 16f, pageWidth - margin, yOffset + 16f, linePaint)
                yOffset += 30f
            }
        }

        // --- TITLE ---
        val titlePaint = TextPaint().apply {
            color = Color.rgb(20, 24, 33) // Dark charcoal
            textSize = 20f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            isAntiAlias = true
        }
        val titleLayout = StaticLayout.Builder.obtain(title, 0, title.length, titlePaint, contentWidth)
            .setAlignment(Layout.Alignment.ALIGN_NORMAL)
            .build()

        canvas.save()
        canvas.translate(margin, yOffset)
        titleLayout.draw(canvas)
        canvas.restore()
        yOffset += titleLayout.height + 6f

        // --- METADATA (Date, Category) ---
        val dateStr = SimpleDateFormat("MMMM d, yyyy · h:mm a", Locale.getDefault()).format(Date(createdAt))
        val metaPaint = TextPaint().apply {
            color = Color.rgb(80, 90, 110)
            textSize = 10f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
            isAntiAlias = true
        }
        canvas.drawText("Date: $dateStr  |  Category: $category  |  AudioPen AI Note", margin, yOffset + 10f, metaPaint)
        yOffset += 18f

        // Accent Divider Bar
        val barPaint = Paint().apply {
            color = Color.rgb(0, 194, 255) // Electric Blue Accent
            strokeWidth = 2.5f
        }
        canvas.drawLine(margin, yOffset, margin + 80f, yOffset, barPaint)
        val subtleLinePaint = Paint().apply {
            color = Color.rgb(220, 225, 235)
            strokeWidth = 0.8f
        }
        canvas.drawLine(margin + 80f, yOffset, pageWidth - margin, yOffset, subtleLinePaint)
        yOffset += 16f

        // --- EXECUTIVE SUMMARY (If present) ---
        if (summary.isNotBlank()) {
            val summaryTitlePaint = TextPaint().apply {
                color = Color.rgb(0, 120, 180)
                textSize = 12f
                typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
                isAntiAlias = true
            }
            val summaryBodyPaint = TextPaint().apply {
                color = Color.rgb(40, 50, 65)
                textSize = 10.5f
                isAntiAlias = true
            }

            val summaryLayout = StaticLayout.Builder.obtain(summary, 0, summary.length, summaryBodyPaint, contentWidth - 24)
                .setAlignment(Layout.Alignment.ALIGN_NORMAL)
                .setLineSpacing(2f, 1.15f)
                .build()

            val boxHeight = summaryLayout.height + 34f
            newPageIfNeeded(boxHeight)

            // Background Card
            val cardPaint = Paint().apply {
                color = Color.rgb(242, 247, 255) // Light subtle blue tint
                style = Paint.Style.FILL
            }
            val cardStroke = Paint().apply {
                color = Color.rgb(205, 225, 250)
                style = Paint.Style.STROKE
                strokeWidth = 1f
            }
            val rect = RectF(margin, yOffset, pageWidth - margin, yOffset + boxHeight)
            canvas.drawRoundRect(rect, 8f, 8f, cardPaint)
            canvas.drawRoundRect(rect, 8f, 8f, cardStroke)

            canvas.drawText("EXECUTIVE SUMMARY", margin + 12f, yOffset + 18f, summaryTitlePaint)

            canvas.save()
            canvas.translate(margin + 12f, yOffset + 26f)
            summaryLayout.draw(canvas)
            canvas.restore()

            yOffset += boxHeight + 14f
        }

        // --- MAIN CONTENT ---
        val sectionHeadingPaint = TextPaint().apply {
            color = Color.rgb(25, 30, 45)
            textSize = 12f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            isAntiAlias = true
        }

        newPageIfNeeded(30f)
        canvas.drawText("STRUCTURED NOTE", margin, yOffset + 12f, sectionHeadingPaint)
        yOffset += 20f

        val bodyPaint = TextPaint().apply {
            color = Color.rgb(30, 35, 45)
            textSize = 11f
            isAntiAlias = true
        }

        val paragraphs = polishedText.split("\n\n")
        paragraphs.forEach { paragraph ->
            if (paragraph.isNotBlank()) {
                val pLayout = StaticLayout.Builder.obtain(paragraph.trim(), 0, paragraph.trim().length, bodyPaint, contentWidth)
                    .setAlignment(Layout.Alignment.ALIGN_NORMAL)
                    .setLineSpacing(2.5f, 1.2f)
                    .build()

                newPageIfNeeded(pLayout.height.toFloat() + 10f)

                canvas.save()
                canvas.translate(margin, yOffset)
                pLayout.draw(canvas)
                canvas.restore()

                yOffset += pLayout.height + 10f
            }
        }

        // --- KEY TAKEAWAYS (If present) ---
        if (keyTakeaways.isNotEmpty()) {
            yOffset += 8f
            newPageIfNeeded(30f)
            canvas.drawText("KEY TAKEAWAYS", margin, yOffset + 12f, sectionHeadingPaint)
            yOffset += 20f

            keyTakeaways.forEach { takeaway ->
                val bulletText = "•  $takeaway"
                val bulletLayout = StaticLayout.Builder.obtain(bulletText, 0, bulletText.length, bodyPaint, contentWidth)
                    .setAlignment(Layout.Alignment.ALIGN_NORMAL)
                    .setLineSpacing(2f, 1.15f)
                    .build()

                newPageIfNeeded(bulletLayout.height.toFloat() + 6f)

                canvas.save()
                canvas.translate(margin, yOffset)
                bulletLayout.draw(canvas)
                canvas.restore()

                yOffset += bulletLayout.height + 6f
            }
        }

        // --- ACTION CHECKLIST (If present) ---
        if (checklist.isNotEmpty()) {
            yOffset += 8f
            newPageIfNeeded(30f)
            val taskHeadingPaint = TextPaint().apply {
                color = Color.rgb(0, 140, 90) // Emerald tone
                textSize = 12f
                typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
                isAntiAlias = true
            }
            canvas.drawText("ACTION ITEMS & TO-DOS", margin, yOffset + 12f, taskHeadingPaint)
            yOffset += 20f

            checklist.forEach { item ->
                val checkSymbol = if (item.isCompleted) "[✓] " else "[  ] "
                val fullItemText = "$checkSymbol ${item.text}"
                val itemPaint = TextPaint().apply {
                    color = if (item.isCompleted) Color.GRAY else Color.rgb(30, 35, 45)
                    textSize = 10.5f
                    isAntiAlias = true
                }

                val itemLayout = StaticLayout.Builder.obtain(fullItemText, 0, fullItemText.length, itemPaint, contentWidth)
                    .setAlignment(Layout.Alignment.ALIGN_NORMAL)
                    .build()

                newPageIfNeeded(itemLayout.height.toFloat() + 6f)

                canvas.save()
                canvas.translate(margin, yOffset)
                itemLayout.draw(canvas)
                canvas.restore()

                yOffset += itemLayout.height + 6f
            }
        }

        // --- FOOTER ON FINAL PAGE ---
        val footerPaint = TextPaint().apply {
            color = Color.GRAY
            textSize = 8.5f
            isAntiAlias = true
        }
        canvas.drawText("Generated by AudioPen AI Voice Memo App", margin, pageHeight - 20f, footerPaint)

        pdfDoc.finishPage(page)

        val safeTitle = title.replace("[^a-zA-Z0-9.-]".toRegex(), "_").take(30)
        val file = File(context.cacheDir, "${safeTitle}_export.pdf")
        val outputStream = FileOutputStream(file)
        pdfDoc.writeTo(outputStream)
        outputStream.close()
        pdfDoc.close()

        return file
    }

    /**
     * Share any file (TXT, MD, PDF) via Android Sharesheet
     */
    fun shareFile(
        context: Context,
        file: File,
        mimeType: String,
        title: String
    ) {
        val uri: Uri = FileProvider.getUriForFile(
            context,
            "${context.packageName}.fileprovider",
            file
        )

        val intent = Intent(Intent.ACTION_SEND).apply {
            type = mimeType
            putExtra(Intent.EXTRA_STREAM, uri)
            putExtra(Intent.EXTRA_SUBJECT, title)
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }

        val chooser = Intent.createChooser(intent, "Share \"$title\" via...")
        chooser.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_GRANT_READ_URI_PERMISSION)
        context.startActivity(chooser)
    }

    /**
     * Share plain text directly via Sharesheet
     */
    fun shareText(
        context: Context,
        text: String,
        subject: String
    ) {
        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(Intent.EXTRA_SUBJECT, subject)
            putExtra(Intent.EXTRA_TEXT, text)
        }
        val chooser = Intent.createChooser(intent, "Share note text via...")
        chooser.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        context.startActivity(chooser)
    }
}
